### ISSUE TITLE
Class as an SVGAttribute

### ISSUE THREAD

**Issue by sodaplayer** [mithril-icons/builder#1]
Hey there, awesome project! I was pretty stoked to find types for icons in Mithril. Just wanted to add a request for `class` be added to the SVGAttributes Interface. I've been seeing some CSS frameworks providing utilities to style SVG icons.

Thanks!

**Comment by kijowski** [comment]
Hi!
Sorry for not replying earlier but I've missed this issue. I've just added base Mithril attributes so adding classes should work now :)

**Comment by sodaplayer** [comment]
No problem at all! Thanks for adding the attributes! :)
